"""add student_id to transaction

Revision ID: 98e07f440c21
Revises: a2aa4f2281af
Create Date: 2025-07-02 00:17:57.110060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e07f440c21'
down_revision = 'a2aa4f2281af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_student_id', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_student_id', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
