"""volunteer student_id relation

Revision ID: a2aa4f2281af
Revises: 
Create Date: 2025-07-01 23:50:02.291933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2aa4f2281af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_volunteers_student_id_students', 'students', ['student_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_volunteers_student_id_students', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
